version: '3'

services:
  app:
    container_name: ${CONTAINER_NAME}
    ports:
      - 80:80
    volumes:
      - ./:/app
      - ./config/docker/nginx.conf:/etc/nginx/nginx.conf
      - ./config/docker/fpm-pool.conf:/etc/php8/php-fpm.d/www.conf
      - ./config/docker/php.ini:/etc/php8/conf.d/custom.ini/
      - ./config/docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    build:
      context: .
      dockerfile: ./Dockerfile
