common_controllers:
  resource: ../../src/Common/Controller/
  type: annotation

admin_controllers:
  resource: ../../src/Admin/Controller
  type: annotation

user_controllers:
  resource: ../../src/User/Controller
  type: annotation

kernel:
  resource: ../../src/Kernel.php
  type: annotation
